# Défini une image de base et met un alias
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# Défini le dossier de travail à /app
WORKDIR /app
# Copie l'entierté du dossier P_Bulle_Docker-ASP.NET
COPY P_Bulle_Docker-ASP.NET/ ./P_Bulle_Docker-ASP.NET/
# Copie l'entierté du dossier test
COPY test/ ./test/
# restore les libraires du csproj
RUN dotnet restore P_Bulle_Docker-ASP.NET/P_Bulle_Docker.csproj
# Il construit l'application
RUN dotnet build P_Bulle_Docker-ASP.NET/P_Bulle_Docker.csproj -c Release
# restore les libraires du csproj
RUN dotnet restore test/test.csproj
# Il construit l'application
RUN dotnet build test/test.csproj -c Release
# Défini le dossier de travail à /app/test
WORKDIR /app/test
# Execute cette commande au déamarage du container
CMD ["dotnet", "test", "test.csproj", "--logger", "trx;LogFileName=test_results.trx", "--results-directory", "/app/test_results"]
