# Fais le build des tests
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# Défini le dossier de travail
WORKDIR /app
# Copie le dossier de l'application
COPY P_Bulle_Docker-ASP.NET/ ./P_Bulle_Docker-ASP.NET/
# Copie le dossier des tests
COPY test/ ./test/
# Restaurer les libraires de l'application
RUN dotnet restore P_Bulle_Docker-ASP.NET/P_Bulle_Docker.csproj
# Build l'application
RUN dotnet build P_Bulle_Docker-ASP.NET/P_Bulle_Docker.csproj -c Release
# Restaurer les libraires des tests
RUN dotnet restore test/test.csproj
# Build les tests
RUN dotnet build test/test.csproj -c Release
# Définir le répertoire de travail pour les tests
WORKDIR /app/test
# Définir la commande pour exécuter les tests et enregistrer les résultats
CMD ["dotnet", "test", "test.csproj", "--logger", "trx;LogFileName=test_results.trx", "--results-directory", "/app/test_results"]
