# Défini la version de docker-compose
version: '3.8'
# Défini les services
services:
  # Défini un service de db
  db:
    # Défini l'image du containeur
    image: mysql:latest
    # Défini des variables d'environment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    # Défini les ports du containeur
    ports:
      - '3306:3306'
    # Défini un volume de db-data
    volumes:
      - db-data:/var/lib/mysql
  # Défini un service de développement
  dev:
    # Défini le build de l'image
    build:
      # Défini le chemin jusqu'au Dockerfile
      context: .
      # Défini le nom du dockerfile
      dockerfile: Dockerfile
      # Défini quel étape prendre
      target: development
    # Défini les ports
    ports:
      - '9721:80'  
      - '443:443'
    # Défini un volume
    volumes:
      - .:/app
    # Dépends de certain service
    depends_on:
      - db
  # Défini un service de test
  test:
    # Défini le build de l'image
    build:
      # Défini le chemin du dockerfile
      context: ..
      # Défini le nom du dockerfile
      dockerfile: Dockerfile.test
    # Défini les dépendances du containeur
    depends_on:
      - db
    # Défini les volumes
    volumes:
      - ../test:/app/test
      - ./test_results:/app/test_results
# Défini les volumes
volumes:
  db-data:
# Défini le réseau
networks:
  default:
