# On défini la version
version: '3.8'

# On va définir les différents services
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ../Database/P_Bulle-Docker.sql:/docker-entrypoint-initdb.d/P_Bulle-Docker.sql
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '9721:80'
    volumes:
      - .:/app
    depends_on:
      - db
  test:
    build:
      context: ..
      dockerfile: Dockerfile.test
    depends_on:
      - db
    volumes:
      - ../test:/app/test
      - ./test_results:/app/test_results
volumes:
  db-data:
networks:
  default:
