version: '3.8'
services:
  db:
    build:
      context: ../Database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '9721:80'  
      - '443:443'
    volumes:
      - .:/app
    depends_on:
      - db
  test:
    build:
       context: ../test
       dockerfile: Dockerfile
    depends_on:
      - db
      - webapp
volumes:
  db-data:
networks:
  default:
