services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - ENV MYSQL_ROOT_PASSWORD=root
      - ENV MYSQL_DATABASE=mysqldatabaser
    volumes:
      - my-db:/var/lib/mysql
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: application
    depends_on:
      - db
  test:
    build:
      context: ../TestUnitaire/test
      dockerfile: Dockerfile
    container_name: test
    depends_on:
      - db
      - webapp
volumes:
  my-db:
  