services:
  db:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysqldatabaser
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  webapp:
    container_name: aspnet
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    ports:
      - '8082'
      - '4430'
    volumes:
      - ~/.aspnet/https:/https:ro
volumes:
  my-db:
  